// <auto-generated />
using System;
using ArchiveSearch.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArchiveSearch.Data.Migrations
{
    [DbContext(typeof(ArchiveContext))]
    [Migration("20260228010324_AddCollectionRequests")]
    partial class AddCollectionRequests
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("ArchiveSearch.Data.Entities.CollectionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Abstract")
                        .HasColumnType("TEXT")
                        .HasColumnName("abstract");

                    b.Property<string>("BiogHist")
                        .HasColumnType("TEXT")
                        .HasColumnName("biog_hist");

                    b.Property<string>("CollectionUnitId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("collection_unitid");

                    b.Property<string>("CompactLine")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("compact_line");

                    b.Property<string>("Corpnames")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("corpnames");

                    b.Property<int?>("DateEnd")
                        .HasColumnType("INTEGER")
                        .HasColumnName("date_end");

                    b.Property<string>("DateRange")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_range");

                    b.Property<int?>("DateStart")
                        .HasColumnType("INTEGER")
                        .HasColumnName("date_start");

                    b.Property<string>("Extent")
                        .HasColumnType("TEXT")
                        .HasColumnName("extent");

                    b.Property<string>("Genres")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("genres");

                    b.Property<string>("Geognames")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("geognames");

                    b.Property<string>("Persnames")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("persnames");

                    b.Property<string>("Repository")
                        .HasColumnType("TEXT")
                        .HasColumnName("repository");

                    b.Property<string>("ScopeContent")
                        .HasColumnType("TEXT")
                        .HasColumnName("scope_content");

                    b.Property<string>("SeriesTitles")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("series_titles");

                    b.Property<string>("SourceFile")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_file");

                    b.Property<string>("Subjects")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("subjects");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("CollectionUnitId")
                        .IsUnique();

                    b.ToTable("collections");
                });

            modelBuilder.Entity("ArchiveSearch.Data.Entities.CollectionRequestEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Affiliation")
                        .HasColumnType("TEXT")
                        .HasColumnName("affiliation");

                    b.Property<string>("CollectionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("collections_json");

                    b.Property<bool>("EmailSent")
                        .HasColumnType("INTEGER")
                        .HasColumnName("email_sent");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("RequesterEmail")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("requester_email");

                    b.Property<string>("RequesterName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("requester_name");

                    b.Property<string>("RequesterPhone")
                        .HasColumnType("TEXT")
                        .HasColumnName("requester_phone");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("submitted_at");

                    b.HasKey("Id");

                    b.ToTable("collection_requests");
                });
#pragma warning restore 612, 618
        }
    }
}
