// <auto-generated />
using ArchiveSearch.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArchiveSearch.Data.Migrations
{
    [DbContext(typeof(ArchiveContext))]
    [Migration("20260212000239_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArchiveSearch.Data.Entities.CollectionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abstract")
                        .HasColumnType("text")
                        .HasColumnName("abstract");

                    b.Property<string>("BiogHist")
                        .HasColumnType("text")
                        .HasColumnName("biog_hist");

                    b.Property<string>("CollectionUnitId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("collection_unitid");

                    b.Property<string>("CompactLine")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("compact_line");

                    b.PrimitiveCollection<string[]>("Corpnames")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("corpnames");

                    b.Property<int?>("DateEnd")
                        .HasColumnType("integer")
                        .HasColumnName("date_end");

                    b.Property<string>("DateRange")
                        .HasColumnType("text")
                        .HasColumnName("date_range");

                    b.Property<int?>("DateStart")
                        .HasColumnType("integer")
                        .HasColumnName("date_start");

                    b.Property<string>("Extent")
                        .HasColumnType("text")
                        .HasColumnName("extent");

                    b.PrimitiveCollection<string[]>("Genres")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("genres");

                    b.PrimitiveCollection<string[]>("Geognames")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("geognames");

                    b.PrimitiveCollection<string[]>("Persnames")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("persnames");

                    b.Property<string>("Repository")
                        .HasColumnType("text")
                        .HasColumnName("repository");

                    b.Property<string>("ScopeContent")
                        .HasColumnType("text")
                        .HasColumnName("scope_content");

                    b.PrimitiveCollection<string[]>("SeriesTitles")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("series_titles");

                    b.Property<string>("SourceFile")
                        .HasColumnType("text")
                        .HasColumnName("source_file");

                    b.PrimitiveCollection<string[]>("Subjects")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("subjects");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("CollectionUnitId")
                        .IsUnique();

                    b.ToTable("collections");
                });
#pragma warning restore 612, 618
        }
    }
}
